management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging.level:
  org.springframework.data: warn

spring:
  profiles:
    active: azure
  flyway:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://any.uaa.uri/token_keys

animal-rescue:
  adoption-request-limit: 10